### ISSUE TITLE
Please rename project to `micrometer-samples-spring-boot`

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer-samples-spring-boot#1]
`boot` is a term that shouldn't be used in module names (it is unqualified). I don't think the 2 part is very relevant considering you have the term `legacy` for Spring Boot 1.x

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/38809976-ff7de086-414a-11e8-9b09-21e6e6f8e8a5.png)
