### ISSUE TITLE
Configuring for new relic

### ISSUE THREAD

**Issue by mghildiy** [micrometer-metrics/micrometer-samples-spring-boot#5]
Hi,

I am following this [link](https://micrometer.io/docs/registry/new-relic).

It asks to implement NewRelicConfig  and create NewRelicMeterRegistry with it.
But where do I need to place this code in springboot 2 application.
Posted on SO too:

https://stackoverflow.com/questions/50551778/configuring-new-relic-in-sping-boot-with-insight-key

**Comment by jkschneider** [comment]
@mghildiy Those directions assume you are not using Spring Boot. The Spring Boot reference manual indicates how to properly configure new relic: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-export-newrelic
